[package]
name = "spaced_learner"
version = "0.1.0"
authors = ["Sandeep Datta <datta.sandeep@gmail.com>"]
license = "Apache-2.0"

[dependencies]


[dependencies.cursive]
version = "*"
default-features = false
features = ["termion-backend"]
